// <auto-generated />
namespace Odarms.Data.DataContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Migrate4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Migrate4));
        
        string IMigrationMetadata.Id
        {
            get { return "201712250127229_Migrate-4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
